version: "3.7"
services:
  database:
    image: postgres:11
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  nginx_auth:
    image:  nginx_auth
    build: "./nginx_auth/"
    container_name: nginx_auth
    ports:
      - "80:80"
    depends_on:
      - java
  java:
    image: java
    #build: "."
    container_name: java
    environment:
      DATABASE: database
    ports:
      - "9090:9090"
    depends_on:
      - database