version: "3.7"
services:
  database:
    image: postgres:11
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
#  java:
#    image:  java
#    build: "."
#    container_name: java
#    environment:
#      DATABASE: database
#    ports:
#      - "9090:9090"
#  TODO frontend in container
#  web:
#    image:  web
#    build: "./website/"
#    container_name: web
#    ports:
#      - "80:80"
